# Generated by Django 5.1.7 on 2025-03-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kunst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('afbeeld', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('afbeeld_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
