# Generated by Django 5.1.7 on 2025-04-11 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunst',
            name='datum',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
