# Generated by Django 5.1.7 on 2025-04-11 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kunst', '0002_kunst_datum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kunst',
            old_name='datum',
            new_name='created_by',
        ),
    ]
