# Generated by Django 5.1.7 on 2025-05-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunst', '0003_rename_datum_kunst_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('afbeeld', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
