# Generated by Django 5.1.7 on 2025-05-30 15:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunst', '0004_decor'),
    ]

    operations = [
        migrations.AddField(
            model_name='decor',
            name='created_by',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
