# Generated by Django 5.1.7 on 2025-05-31 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunst', '0005_decor_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Werk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('afbeeld', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_by', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
