# Generated by Django 5.1.7 on 2025-06-24 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kunst', '0006_werk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kunst',
            name='afbeeld',
        ),
        migrations.RemoveField(
            model_name='kunst',
            name='afbeeld_name',
        ),
    ]
