# Generated by Django 5.1.7 on 2025-06-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunst', '0007_remove_kunst_afbeeld_remove_kunst_afbeeld_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunst',
            name='afbeeld',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
