# Generated by Django 5.1.7 on 2025-06-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunst', '0008_kunst_afbeeld'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunst',
            name='formaat',
            field=models.CharField(default='algemeen', max_length=200),
        ),
        migrations.AddField(
            model_name='kunst',
            name='materiaal',
            field=models.CharField(default='algemeen', max_length=200, null=True),
        ),
    ]
