# Generated by Django 5.1.7 on 2025-06-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunst', '0010_kunst_jaartal'),
    ]

    operations = [
        migrations.AddField(
            model_name='decor',
            name='formaat',
            field=models.CharField(default='algemeen', max_length=200),
        ),
        migrations.AddField(
            model_name='decor',
            name='jaartal',
            field=models.IntegerField(default='2025', null=True),
        ),
        migrations.AddField(
            model_name='decor',
            name='materiaal',
            field=models.CharField(default='algemeen', max_length=200, null=True),
        ),
    ]
