# Generated by Django 5.1.7 on 2025-06-25 09:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunst', '0011_decor_formaat_decor_jaartal_decor_materiaal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afbeeld', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_by', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
