# Generated by Django 5.1.7 on 2025-09-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunst', '0012_tent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tent',
            name='titel',
            field=models.CharField(default='geen', max_length=200),
        ),
    ]
