# Generated by Django 5.1.7 on 2025-09-03 14:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunst', '0013_tent_titel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Bezoekers Dashboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('page', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
