# Generated by Django 5.1.7 on 2025-09-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kunst', '0014_visitordashboard_visitor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitordashboard',
            options={'managed': False, 'verbose_name': 'Bezoekers Dashboard', 'verbose_name_plural': 'Bezoekers Dashboard'},
        ),
    ]
