# Generated by Django 5.1.7 on 2025-09-03 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kunst', '0015_alter_visitordashboard_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorDashboard',
        ),
    ]
