# Generated by Django 5.1.7 on 2025-09-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunst', '0016_delete_visitordashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Bezoekers Dashboard',
                'verbose_name_plural': 'Bezoekers Dashboard',
                'managed': False,
            },
        ),
    ]
